//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_Preprocessing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PredictionEntities : DbContext
    {
        public PredictionEntities()
            : base("name=PredictionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<D_CP> D_CP { get; set; }
        public virtual DbSet<G_CP> G_CP { get; set; }
        public virtual DbSet<U_CP> U_CP { get; set; }
        public virtual DbSet<大眾傳播學群_CP> 大眾傳播學群_CP { get; set; }
        public virtual DbSet<工程學群_CP> 工程學群_CP { get; set; }
        public virtual DbSet<文史哲學群_CP> 文史哲學群_CP { get; set; }
        public virtual DbSet<外語學群_CP> 外語學群_CP { get; set; }
        public virtual DbSet<生命科學學群_CP> 生命科學學群_CP { get; set; }
        public virtual DbSet<生物資源學群_CP> 生物資源學群_CP { get; set; }
        public virtual DbSet<地球與環境學群_CP> 地球與環境學群_CP { get; set; }
        public virtual DbSet<法政學群_CP> 法政學群_CP { get; set; }
        public virtual DbSet<社會與心理學群_CP> 社會與心理學群_CP { get; set; }
        public virtual DbSet<建築與設計學群_CP> 建築與設計學群_CP { get; set; }
        public virtual DbSet<財經學群_CP> 財經學群_CP { get; set; }
        public virtual DbSet<教育學群_CP> 教育學群_CP { get; set; }
        public virtual DbSet<資訊學群_CP> 資訊學群_CP { get; set; }
        public virtual DbSet<遊憩與運動學群_CP> 遊憩與運動學群_CP { get; set; }
        public virtual DbSet<管理學群_CP> 管理學群_CP { get; set; }
        public virtual DbSet<數理化學群_CP> 數理化學群_CP { get; set; }
        public virtual DbSet<醫藥衛生學群_CP> 醫藥衛生學群_CP { get; set; }
        public virtual DbSet<藝術學群_CP> 藝術學群_CP { get; set; }
    }
}
