//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_Preprocessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class 教育學群_CP
    {
        public int ID { get; set; }
        public string Uname { get; set; }
        public string Dname { get; set; }
        public string UDname { get; set; }
        public Nullable<double> MinScore { get; set; }
        public Nullable<double> SalaryInK { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> CP { get; set; }
    }
}
